include: package:very_good_analysis/analysis_options.4.0.0.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "lib/src/api/*"
    - "lib/src/auth/*"
    - "lib/src/model/*"
    - "lib/src/api.dart"
    - "lib/src/deserialize.dart"
