name: k8s
description: Kubernetes client library for Dart.
version: 1.27.0+dev.1
repository: https://github.com/nopso/k8s-dart
issue_tracker: https://github.com/nopso/k8s-dart/issues
documentation: https://k8s-dart.nopso.io/
topics: [kubernetes]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  dio: "^5.4.0"
  json_annotation: ^4.8.1
  kubeconfig: ^1.0.2
  logging: ^1.2.0
  path: ^1.9.0
  socks5_proxy: ^1.0.4

dev_dependencies:
  build_runner: 2.4.8
  json_serializable: ^6.7.1
  test: ^1.25.2
  very_good_analysis: ^5.1.0

screenshots:
  - description: Kubernetes Client for Dart logo
    path: assets/logo.webp

