# Publish to pub.dev
name: Publish

on:
  push:
    tags:
    # must align with the tag-pattern configured on pub.dev admin page
    - 'v[0-9]+.[0-9]+.[0-9]+*' # for tags like: 'v1.2.3'

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      # Specify the github actions deployment environment
      environment: pub.dev
